### ISSUE TITLE
Remove the additional console logging that occurs during testing

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#165]
When you run `npm test` there is a lot of output noise - here's a snippet:

~~~
      at log (src/common/log.js:60:47)

    console.log
       Your API has been forged from the fiery furnace:

      at log (src/common/log.js:60:47)

    console.log
       0 models have been molded

      at log (src/common/log.js:60:47)

    console.log
       0 endpoints have been cast

      at log (src/common/log.js:60:47)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)

    console.log
      Validating generator

      at Object.log [as standard] (src/common/log.js:60:47)

    console.log
      Loading schema from 'openapi.json'

      at Object.log [as standard] (src/common/log.js:60:47)

    console.log
      Iterating over 1 files

      at Object.log [as standard] (src/common/log.js:60:47)

    console.log
      No formatter found in generatorPath

      at Object.log [as error] (src/common/log.js:56:11)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)

    console.log
                  API generation  SUCCESSFUL 

      at log (src/common/log.js:60:47)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)

    console.log
       Your API has been forged from the fiery furnace:

      at log (src/common/log.js:60:47)

    console.log
       0 models have been molded

      at log (src/common/log.js:60:47)

    console.log
       0 endpoints have been cast

      at log (src/common/log.js:60:47)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)

    console.log
      Validating generator

      at Object.log [as standard] (src/common/log.js:60:47)

    console.log
      Loading schema from 'openapi.json'

      at Object.log [as standard] (src/common/log.js:60:47)

    console.log
      Iterating over 1 files

      at Object.log [as standard] (src/common/log.js:60:47)

    console.log
      No formatter found in generatorPath

      at Object.log [as error] (src/common/log.js:56:11)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)

    console.log
                  API generation  SUCCESSFUL 

      at log (src/common/log.js:60:47)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)

    console.log
       Your API has been forged from the fiery furnace:

      at log (src/common/log.js:60:47)

    console.log
       0 models have been molded

      at log (src/common/log.js:60:47)

    console.log
       0 endpoints have been cast

      at log (src/common/log.js:60:47)

    console.log
      
      ---------------------------------------------------

      at log (src/common/log.js:60:47)


Test Suites: 2 passed, 2 total
Tests:       9 passed, 9 total
~~~

This makes it quite hard to locate failing tests. Ideally the console logging from the generator would be suppressed.

**Comment by ms14981** [comment]
Could be a good first issue for someone?
