### ISSUE TITLE
printing of schema validation errors gives error when only one error found

### ISSUE THREAD

**Issue by jhowlett-scottlogic** [ScottLogic/openapi-forge#49]
Make sure that you can loop through the errors object.

CL output

------------------------------------------------------------------------------------------------------------------------------------

Schema validation errors:

---------------------------------------------------

              API generation  FAILED

---------------------------------------------------

TypeError: errors.forEach is not a function
    at isValidSchema (C:\Users\jhowlett\Documents\open_unlock\openapi-forge\src\generate.js:64:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async generate (C:\Users\jhowlett\Documents\open_unlock\openapi-forge\src\generate.js:146:12)

---------------------------------------------------

**Comment by jhowlett-scottlogic** [comment]
make sure `errors.length` is not undefined.

**Comment by jhowlett-scottlogic** [comment]
Possible solution:

```
async function isValidSchema(schema) {
  try {
    await SwaggerParser.validate(cloneSchema(schema));
  } catch (errors) {
    console.error("Schema validation errors:");
    if(errors.length !== undefined) {
      errors.forEach((error) => {
        const err = error.message;
        if(error.instancePath != undefined) {
          err +=  `at ${error.instancePath}`
        }
        console.error(err);
      });
    } else {
      const err = errors.message;
      if(errors.instancePath !== undefined) {
        err +=  `at ${errors.instancePath}`
      }
      console.error(err);
    }
    return false;
  }
  return true;
}
```
